title: <p align="left"> Lopamudra Pradhan </p>
logo: assets/img/logo1.jpeg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://github.com/Lopa0007/">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  <br>
  </p>
theme: jekyll-theme-minimal
